export const RAW_COLORS = {
  black: '#000000',
  white: '#ffffff',
  appBrown: '#282119',
  appBrownDeep: '#1f1a15',
  appBrownTransparent: 'rgba(40, 33, 25, 0)',
  appBrownSoft: '#65371f',
  appCream: '#e5d8bd',
  appRust: '#a54d27',
  appCopper: '#c97338',
  offBlack: '#0a0a0a',
  requestBlack: '#080808',
  popupBlack: '#111',
  popupPanel: '#121212',
  popupCream: '#f3e6cb',
  freewillRed: '#4F0000',
  baziLight: '#eeeeee',
  baziDark: '#454545',
  baziDarkText: '#ececec',
  baziWood: '#44995e',
  baziFire: '#c94b4b',
  baziEarth: '#a3692f',
  baziMetal: '#fcaa06',
  baziWater: '#3078ce',
  almanacSand: '#D9C3A5',
  almanacOcean: '#0B4F6C',
  almanacSky: '#1699B8',
  almanacBrown: '#8A531B',
  almanacSage: '#B7C9A8',
  almanacGrey: '#5A5E66',
  almanacMist: '#E7E2D7',
  glitchWarm: '#d85b5b',
  glitchCool: '#31a8c4',
};

export const alpha = (rgb, value) => `rgba(${rgb}, ${value})`;

export const RGB = {
  black: '0, 0, 0',
  blackTight: '0,0,0',
  white: '255, 255, 255',
  cream: '229, 216, 189',
  creamTight: '229,216,189',
  brown: '40, 33, 25',
  brownTight: '40,33,25',
  rust: '165, 77, 39',
  copper: '201, 115, 56',
  copperTight: '201,115,56',
  requestBlack: '8, 8, 8',
  requestBlackTight: '8,8,8',
  baziDarkText: '236, 236, 236',
  popupCream: '243,230,203',
  popupPanel: '18,18,18',
  freewillRed: '79,0,0',
};

export const FONT_STACKS = {
  display: '"Syne", sans-serif',
  body: '"Space Mono", monospace',
  cjk: '"Noto Sans SC", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Heiti SC", "Source Han Sans SC", "Helvetica Neue", Arial, sans-serif',
  externalDisplay: '"Syne", "Noto Sans SC", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Heiti SC", "Source Han Sans SC", "Helvetica Neue", Arial, sans-serif',
  monoSystem: 'ui-monospace, SFMono-Regular, Menlo, monospace',
  renderBody: 'Space Mono, Noto Sans SC',
  renderDisplay: 'Syne',
  freewill: '"Shamblers"',
  freewillRegular: '"ShamblersRegular"',
  leagueGothic: '"League Gothic"',
  leagueGothicRegular: '"LeagueGothic-Regular"',
};

export const FONT_NAMES = {
  syne: 'Syne',
  spaceMono: 'Space Mono',
  notoSansSc: 'Noto Sans SC',
};

export const GOOGLE_FONT_URLS = {
  app: 'https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400&family=Syne:wght@400;700;800&display=swap',
  external: 'https://fonts.googleapis.com/css2?family=Syne:wght@400;700;800&family=Noto+Sans+SC:wght@400;500;700;800&display=swap',
  notFound: 'https://fonts.googleapis.com/css2?family=Syne:wght@400;700;800&display=swap',
};

export const APP_CSS_VARIABLES = {
  '--bg-primary': RAW_COLORS.appBrown,
  '--bg-secondary': RAW_COLORS.appBrownSoft,
  '--bg-light': RAW_COLORS.appCream,
  '--text-primary': RAW_COLORS.appCream,
  '--text-secondary': alpha(RGB.cream, '0.78'),
  '--text-dark': RAW_COLORS.appBrown,
  '--text-dark-muted': alpha(RGB.brown, '0.74'),
  '--text-dark-soft': alpha(RGB.brown, '0.56'),
  '--text-ghost': alpha(RGB.cream, '0.06'),
  '--text-dark-ghost': alpha(RGB.brown, '0.12'),
  '--accent-primary': RAW_COLORS.appRust,
  '--accent-secondary': RAW_COLORS.appCopper,
  '--border-soft': alpha(RGB.cream, '0.16'),
  '--border-strong': alpha(RGB.cream, '0.34'),
  '--border-dark': alpha(RGB.brown, '0.18'),
  '--border-dark-strong': alpha(RGB.brown, '0.34'),
  '--surface-tint': alpha(RGB.cream, '0.06'),
  '--surface-light': alpha(RGB.brown, '0.04'),
  '--glow-accent': alpha(RGB.copper, '0.22'),
  '--audio-idle-wave': alpha(RGB.cream, '0.32'),
  '--shadow-deep': alpha(RGB.black, '0.28'),
  '--font-body': FONT_STACKS.body,
  '--font-display': FONT_STACKS.display,
  '--font-cjk': FONT_STACKS.cjk,
  '--font-freewill': FONT_STACKS.freewill,
  '--font-freewill-regular': FONT_STACKS.freewillRegular,
  '--font-league-gothic': FONT_STACKS.leagueGothic,
  '--font-league-gothic-regular': FONT_STACKS.leagueGothicRegular,
  '--bazi-background-light': RAW_COLORS.baziLight,
  '--bazi-foreground-light': RAW_COLORS.offBlack,
  '--bazi-muted-foreground-light': alpha(RGB.black, '0.56'),
  '--bazi-border-light': RAW_COLORS.black,
  '--bazi-main-light': RAW_COLORS.black,
  '--bazi-main-foreground-light': RAW_COLORS.white,
  '--bazi-background-dark': RAW_COLORS.baziDark,
  '--bazi-foreground-dark': RAW_COLORS.baziDarkText,
  '--bazi-muted-foreground-dark': alpha(RGB.baziDarkText, '0.58'),
  '--bazi-element-water': RAW_COLORS.baziWater,
  '--bazi-element-earth': RAW_COLORS.baziEarth,
  '--bazi-element-fire': RAW_COLORS.baziFire,
  '--bazi-element-metal': RAW_COLORS.baziMetal,
  '--bazi-element-wood': RAW_COLORS.baziWood,
  '--bazi-grid-light-line': alpha(RGB.black, '0.16'),
  '--bazi-grid-dark-line': alpha(RGB.white, '0.14'),
  '--bazi-modal-scrim': alpha(RGB.black, '0.44'),
  '--request-panel-bg': alpha(RGB.brownTight, '0.88'),
  '--request-dark-004': alpha(RGB.requestBlackTight, '0.04'),
  '--request-dark-012': alpha(RGB.requestBlackTight, '0.12'),
  '--request-dark-016': alpha(RGB.requestBlackTight, '0.16'),
  '--request-dark-018': alpha(RGB.requestBlackTight, '0.18'),
  '--request-dark-020': alpha(RGB.requestBlackTight, '0.2'),
  '--request-dark-022': alpha(RGB.requestBlackTight, '0.22'),
  '--request-copper-005': alpha(RGB.copperTight, '0.05'),
  '--request-copper-008': alpha(RGB.copperTight, '0.08'),
  '--request-copper-010': alpha(RGB.copperTight, '0.1'),
  '--request-copper-012': alpha(RGB.copperTight, '0.12'),
  '--request-copper-014': alpha(RGB.copperTight, '0.14'),
  '--request-copper-016': alpha(RGB.copperTight, '0.16'),
  '--request-copper-018': alpha(RGB.copperTight, '0.18'),
  '--request-copper-020': alpha(RGB.copperTight, '0.2'),
  '--request-copper-028': alpha(RGB.copperTight, '0.28'),
  '--request-copper-040': alpha(RGB.copperTight, '0.4'),
  '--request-copper-050': alpha(RGB.copperTight, '0.5'),
  '--request-copper-055': alpha(RGB.copperTight, '0.55'),
  '--request-copper-058': alpha(RGB.copperTight, '0.58'),
  '--request-copper-060': alpha(RGB.copperTight, '0.6'),
  '--request-copper-085': alpha(RGB.copperTight, '0.85'),
  '--request-copper-090': alpha(RGB.copperTight, '0.9'),
  '--request-copper-094': alpha(RGB.copperTight, '0.94'),
  '--request-copper-095': alpha(RGB.copperTight, '0.95'),
  '--request-copper-096': alpha(RGB.copperTight, '0.96'),
  '--request-cream-008': alpha(RGB.creamTight, '0.08'),
  '--request-cream-016': alpha(RGB.creamTight, '0.16'),
  '--request-cream-018': alpha(RGB.creamTight, '0.18'),
  '--request-cream-020': alpha(RGB.creamTight, '0.2'),
  '--request-cream-024': alpha(RGB.creamTight, '0.24'),
  '--request-cream-028': alpha(RGB.creamTight, '0.28'),
  '--request-cream-032': alpha(RGB.creamTight, '0.32'),
  '--request-cream-034': alpha(RGB.creamTight, '0.34'),
  '--request-cream-042': alpha(RGB.creamTight, '0.42'),
  '--request-cream-084': alpha(RGB.creamTight, '0.84'),
  '--request-cream-085': alpha(RGB.creamTight, '0.85'),
  '--freewill-background': RAW_COLORS.freewillRed,
  '--freewill-shadow': alpha(RGB.freewillRed, '0.9'),
  '--latent-gradient-stop': RAW_COLORS.appBrownDeep,
  '--glitch-warm': RAW_COLORS.glitchWarm,
  '--glitch-cool': RAW_COLORS.glitchCool,
  '--distortion-scanline-a': alpha(RGB.brownTight, '0'),
  '--distortion-scanline-b': alpha(RGB.brownTight, '0.18'),
  '--distortion-scanline-c': alpha(RGB.copperTight, '0.08'),
  '--distortion-scanline-d': alpha(RGB.creamTight, '0.03'),
  '--distortion-scanline-e': alpha(RGB.rust, '0.08'),
  '--external-background': RAW_COLORS.white,
  '--external-foreground': RAW_COLORS.black,
  '--external-rule-soft': alpha(RGB.black, '0.14'),
  '--external-rule-strong': alpha(RGB.black, '0.18'),
  '--popup-background': RAW_COLORS.popupBlack,
  '--popup-foreground': RAW_COLORS.popupCream,
  '--popup-border-strong': alpha(RGB.popupCream, '0.25'),
  '--popup-border-soft': alpha(RGB.popupCream, '0.16'),
  '--popup-panel': alpha(RGB.popupPanel, '0.92'),
  '--popup-image-shadow': alpha(RGB.blackTight, '0.35'),
};

export const BAZI_COLORS = {
  lightBackground: RAW_COLORS.baziLight,
  darkBackground: RAW_COLORS.baziDark,
  black: RAW_COLORS.black,
  white: RAW_COLORS.white,
  wood: RAW_COLORS.baziWood,
  fire: RAW_COLORS.baziFire,
  earth: RAW_COLORS.baziEarth,
  metal: RAW_COLORS.baziMetal,
  water: RAW_COLORS.baziWater,
};

export const ALMANAC_LUCKY_COLORS = {
  sand: RAW_COLORS.almanacSand,
  ocean: RAW_COLORS.almanacOcean,
  sky: RAW_COLORS.almanacSky,
  brown: RAW_COLORS.almanacBrown,
  sage: RAW_COLORS.almanacSage,
  grey: RAW_COLORS.almanacGrey,
  mist: RAW_COLORS.almanacMist,
};

export const APP_STYLES = {
  heroBackground: {
    background: 'linear-gradient(135deg, var(--bg-primary) 0%, var(--bg-primary) 48%, var(--bg-secondary) 100%)',
  },
  warmOverlay: {
    background:
      `radial-gradient(circle at center, ${alpha(RGB.copper, '0.18')} 0%, ${alpha(RGB.rust, '0.08')} 35%, ${RAW_COLORS.appBrownTransparent} 70%)`,
  },
  heroGlow: {
    background:
      `radial-gradient(circle at 76% 24%, ${alpha(RGB.copper, '0.2')} 0%, ${alpha(RGB.rust, '0.06')} 34%, ${RAW_COLORS.appBrownTransparent} 72%)`,
  },
  toolsMeshPrimary: {
    backgroundImage: [
      'linear-gradient(to right, var(--request-cream-016) 1px, transparent 1px)',
      'linear-gradient(to bottom, var(--request-cream-016) 1px, transparent 1px)',
    ].join(','),
    backgroundSize: '68px 68px, 68px 68px',
  },
  toolsMeshSecondary: {
    backgroundImage: [
      'linear-gradient(to right, var(--request-copper-016) 1px, transparent 1px)',
      'linear-gradient(to bottom, var(--request-copper-016) 1px, transparent 1px)',
    ].join(','),
    backgroundSize: '18px 18px, 18px 18px',
  },
  panelShadow: {
    boxShadow: '0 20px 40px var(--shadow-deep)',
  },
  requestTerminalPanel: {
    backgroundImage: [
      'linear-gradient(180deg, var(--request-dark-020) 0%, var(--request-dark-004) 100%)',
      'linear-gradient(var(--request-copper-008) 1px, transparent 1px)',
      'linear-gradient(90deg, var(--request-copper-008) 1px, transparent 1px)',
    ].join(','),
    backgroundSize: '100% 100%, 100% 26px, 26px 100%',
    backgroundPosition: '0 0, 0 0, 0 0',
  },
  routeViewport: { minHeight: '100dvh' },
  bottomRail: { bottom: 'calc(5rem + env(safe-area-inset-bottom, 0px))' },
  landingContent: {
    paddingTop: 'calc(5rem + env(safe-area-inset-top, 0px))',
    paddingBottom: 'calc(2rem + env(safe-area-inset-bottom, 0px))',
  },
  requestPanel: {
    maxHeight: 'calc(100dvh - env(safe-area-inset-top, 0px) - env(safe-area-inset-bottom, 0px) - 2rem)',
  },
  thanksContent: {
    paddingTop: 'calc(2rem + env(safe-area-inset-top, 0px))',
    paddingBottom: 'calc(2rem + env(safe-area-inset-bottom, 0px))',
  },
  topLeftBackButton: {
    top: 'calc(1rem + env(safe-area-inset-top, 0px))',
  },
};
